-- AlterTable
ALTER TABLE `DemandeConsultation` ADD COLUMN `annuleeParId` VARCHAR(191) NULL,
    ADD COLUMN `annuleeLe` DATETIME(3) NULL,
    MODIFY `statut` ENUM('EN_ATTENTE', 'VALIDEE', 'REFUSEE', 'ANNULEE') NOT NULL DEFAULT 'EN_ATTENTE';

-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('NOUVELLE_DEMANDE', 'DEMANDE_ACCEPTEE', 'DEMANDE_REFUSEE', 'NOUVELLE_PRESCRIPTION', 'PRESCRIPTION_MODIFIEE', 'PRESCRIPTION_SUPPRIMEE', 'CONSULTATION_ANNULEE') NOT NULL;

-- AddForeignKey
ALTER TABLE `DemandeConsultation` ADD CONSTRAINT `DemandeConsultation_annuleeParId_fkey` FOREIGN KEY (`annuleeParId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
